DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI4NTkwNDIwLCJ1c2VySWQiOjJ9.f1BtIDHnJT8T7VGHNXRyoxLcaSxQDZrQcOHsb8QyD50